export { default as Briefing } from './Briefing';
export { default as Depth } from './Depth';
export { default as Landing } from './Landing';
export { default as Region } from './Region';
export { default as Review } from './Review';
export { default as Staining } from './Staining';
export { default as StainingGuide } from './StainingGuide';
export { default as Result } from './Result';
export { default as PrivacyPolicy } from './PrivacyPolicy';